### ISSUE TITLE
amend code to return values of whole playlist

### ISSUE THREAD

**Issue by scottpgreen1972** [bendodson/media-library-access-in-ios-10#1]
Hi Ben,

Great little snippet of code. Thanks for posting it up.

Forgive the complete newbie question, but how would I amend the media query to return the title of every song in my playlist?

I'm guessing it would be by way of a for...loop, but I have no idea how to implement it. My clumsy attempts have all crashed and burned!

Any guidance you could give would be greatly appreciated.

**Comment by bendodson** [comment]
Hey,

Here's a gist with an example of how you could iterate through a playlist and fetch items: https://gist.github.com/bendodson/d842769c2d6f29280e55231e3c0cc5f8

The basic gist (ha!) is that you do an `MPMediaQuery.playlists()` search and then iterate through the collections. You can then check what playlist you are looking at with the `MPMediaPlaylistPropertyName` and if it is the one you want iterate through the items array to get each track.

Hope that helps!
