### ISSUE TITLE
Re-asking for permission

### ISSUE THREAD

**Issue by rikola** [bendodson/media-library-access-in-ios-10#2]
If a user denies the Media Library permission the first time, is there a way to ask for permission again later, such as an app re-launch? 

Based on my experiments, it seems that when the query is run on subsequent launches it just uses whatever the initial response was. It's a bit unintuitive that it pushes the option permanently to the Settings->Privacy->Media_Library menu.

The Apple documentation on the MediaPlayer framework is pretty abysmal and I was wondering if you found anything out.

**Comment by bendodson** [comment]
Hey,

Unfortunately the Media Library permission is the same as all other iOS permissions (location, contacts, calendars, notifications, etc) in that you only get one shot on asking for permission unless they delete and re-install the app. If the user denies the request, the only way for them to enable the permission is to go into the App Settings and manually turn it on.

My recommended flow is that you check the authorisation state and if it is Denied then you show an alert with an option to take the user to the app settings page. You can use `UIApplication.shared.open(URL(string: UIApplicationOpenSettingsURLString)!, options: [:], completionHandler: nil)` to then open the Settings app on your app page where users will then see the Media Library permission (i.e. you don't need to go to Settings > Privacy > Media Library, iOS will automatically generate you a settings page and include it after you first request permission).

Hope that helps!

**Comment by bendodson** [comment]
I just updated the code to include this "Open Settings" link in the error message.
